### ISSUE TITLE
Required status checks don't run after the commit containing the compressed images is added to the pull request

### ISSUE THREAD

**Issue by brendanHearX** [namoscato/action-tinify#416]
Our repo has multiple required status checks that must pass in order for the pull request to be allowed to be merged.

When the commit is created by the Tinify GitHub action containing the compressed image(s), the status checks do not run, and this leaves the pull request in a permanent pending state:
![Screenshot 2023-12-05 at 3 56 14 PM](https://github.com/namoscato/action-tinify/assets/131784920/bc0bcad7-0278-4432-a3da-484aada34255)

How can this be resolved? Is there a reason the status checks are not running again when the commit with the compressed image(s) is created?

See no yellow circle or green checkmark on the `Compress image` commit indicating the checks are running or complete:
![Screenshot 2023-12-05 at 3 56 03 PM](https://github.com/namoscato/action-tinify/assets/131784920/ad2c6bcd-33a5-41f2-8520-2b010dfe17b6)

I've tried several changes to try fix the issue including using a personal access token instead of the repo `GITHUB_TOKEN`. There are also no filters on the required status checks that would prevent them from running after the commit.

Any solutions or suggestions would be greatly appreciated.

**Comment by namoscato** [comment]
👋🏻 @brendanHearX, it is probably because you're _checking out_ the repository with the default token. The pull request event triggered by a `GITHUB_TOKEN` task [will not create](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow) a new workflow run to prevent accidental recursion.

If you're sure that you want the commit to trigger a workflow run, you can configure [`actions/checkout`](https://github.com/actions/checkout) with your personal access token (PAT), i.e.

```yaml
- uses: actions/checkout@v4
  with:
    ref: ${{ github.head_ref }}
    token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
- uses: namoscato/action-tinify@v1
  with:
    api_key: ${{ secrets.TINIFY_API_KEY }}
```

Let me know if that works, and I might drop a note in the README.
